
var LoadJson = LoadJson || {};

/**
 * Load the posts.json data generated by m2j
 * @src http://codepen.io/KryptoniteDove/post/load-json-file-locally-using-pure-javascript
 * 
 * @static
 * @param callback which retrieve the returned data
 */
loadJson = function(file, callback) {
    var xobj = new XMLHttpRequest();
    xobj.overrideMimeType("application/json");
    xobj.open('GET', Data.config.path.baseurl+'/'+file, true);
    /**
     * Function to run when data is returned successfully
     */
    xobj.onreadystatechange = function() {
        if (xobj.readyState == 4 && xobj.status == 200) {

            callback(xobj.responseText);
        }
    };
    xobj.send(null);
};