module Post {
    /**
     * Controller for loading/showing posts
     * 
     * @export
     * @class PostController
     */
    export class PostController {
      
        /**
         * Variable holding post data loaded from json file
         * 
         * @static
         * @type {JSON}
         */
        static posts: Array<Object>;

        /**
         * Initializes the post page and load posts
         */
        static initPage() {
            if (this.posts == null)
                this.loadJson(function(response) {
                    PostController.posts = JSON.parse(response);//parse actual json retrieved
                    PostController.renderPosts();

                });
            else
                this.renderPosts();
        }
        
        
        /**
         * Renders posts loaded
         * 
         * @static
         */
        static renderPosts() {
            var html = "";
            for (var i = 0; i < this.posts.length; ++i) {
                html += Spa.App.namespace['postListMd'](this.posts[i]);
            }

            document.getElementById("posts").innerHTML = html;
        }


        /**
         * Load the posts.json data generated by m2j
         * @src http://codepen.io/KryptoniteDove/post/load-json-file-locally-using-pure-javascript
         * 
         * @static
         * @param callback which retrieve the returned data
         */
        static loadJson(callback) {
            var xobj = new XMLHttpRequest();
            xobj.overrideMimeType("application/json");
            xobj.open('GET', 'posts.json', true);
            /**
             * Function to run when data is returned successfully
             */
            xobj.onreadystatechange = function() {
                if (xobj.readyState == 4 && xobj.status == 200) {

                    callback(xobj.responseText);
                }
            };
            xobj.send(null);
        }
    }
}